/**
 * This file was generated by the JPA Modeler
 */
package com.arealab.BdTScuola.entity;

import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * @author Pingu
 */
@Entity
public class Docente {

    @Id
    @GeneratedValue
    private Long id;
    @Basic
    private String nome;
    @Basic
    private String cognome;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNome() {
        return nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getCognome() {
        return cognome;
    }

    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

}